server:
  port: 39061

spring:
  redis:
    host: 10.147.1.90
    port: 6379
    password:
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms