################################################################################
# SPRING BOOT, BATCH DEMO EXAMPLE
################################################################################

spring:
  application:
    name: "SPRING-BATCH-EXAMPLE"

  output:
    ansi:
      enabled: ALWAYS

  main:
    web-application-type: SERVLET

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/acquire;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.type: trace
#    com.querydsl.sql: trace

server:
  port: 9000
