################################################################################
# SPRING BOOT, BATCH DEMO EXAMPLE
################################################################################

spring:
  profiles:
    active: local

  application:
    name: "SPRING-BATCH-EXAMPLE"

  output:
    ansi:
      enabled: ALWAYS

  main:
    web-application-type: SERVLET


logging:
  level:
    org.hibernate.type: trace
#    com.querydsl.sql: trace

server:
  port: 9000

---
spring:
  profiles: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/acquire;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate.format_sql: true

  batch:
    #    table-prefix:
    #    schema:
    job:
      #      names: job1,job2
      # 스프링 배치 작업을 자동으로 실행시키지 않으려면 false, 기본은 true
      enabled: false
    initialize-schema: EMBEDDED


---
spring:
  profiles: prod

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
      jdbc-url: jdbc:mysql://127.0.0.1:3306/springbatch?autoReconnect=true&useSSL=false&serverTimezone=UTC
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate.format_sql: true
  batch:
    #    table-prefix:
    #    schema:
    job:
      enabled: false
    initialize-schema: ALWAYS # 임시로 always 사용..
