
spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/agent?characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 60000

  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: false
#      hibernate.jdbc.batch_size: 10
#      hibernate.jdbc.batch_versioned_data: true
#      hibernate.order_insert: true
#      hibernate.order_update: true
#      hibernate.enable_lazy_load_no_trans: true

  redis:
    host: '127.0.0.1'
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
#        time-between-eviction-runs:
      cluster:
        refresh:
          adaptive: false
#          period:
      shutdown-timeout: 100ms
    database: 0
    ssl: false





logging:
  level:
    com.querydsl.sql: INFO
    org.hibernate.type: INFO


imc:
  crawler:
    web-driver:
      key: 'webdriver.chrome.driver'
      value: 'chromedriver.exe'
      implicitly-wait: 10
      options:
#        - '--headless'
#        - '--no-sandbox'
#        - '--disable-dev-shm-usage'
    scheduled:
      welcome: '*/5 * * * * *'
      deposit-guide: '*/5 * * * * *'
      board: '*/5 * * * * *'
      without-bankbook: '*/5 * * * * *'


      load-mall-admin: '10 20 */1 * * *'
      load-mall-user: '40 */1 * * * *'