
spring:
  output:
    ansi:
      enabled: ALWAYS

imc:
  crawler:
    web-driver:
      key: 'webdriver.chrome.driver'
      value: src/main/resources/chromedriver.exe
      options:
#        - '--headless'
#        - '--no-sandbox'
#        - '--disable-dev-shm-usage'
#      value: 'chromedriver'