
spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crawler?characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 60000

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

logging:
  level:
    com.querydsl.sql: trace
    org.hibernate.type: trace


imc:
  crawler:
    web-driver:
      key: 'webdriver.chrome.driver'
      value: src/main/resources/chromedriver.exe
      options:
#        - '--headless'
#        - '--no-sandbox'
#        - '--disable-dev-shm-usage'
#      value: 'chromedriver'