server:
  port: 9999
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 60m

spring:
  mvc:
    view:
      prefix: /resource/static/
      suffix: .html
    locale: ko_KR

  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 20MB

  resources:
    chain:
      compressed: true
      cache: true

  datasource:
    url: jdbc:mysql://localhost:3306/imc_admin?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      default-auto-commit: false
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-idle: 30
      max-wait: 10000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 130000
      min-evictable-idle-time-millis: 120000
      num-tests-per-eviction-run: 20
      remove-abandoned: true
      remove-abandoned-timeout: 30
      log-abandoned: false
      validation-query: 'select 1 from dual'
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 60000
  output:
    ansi:
      enabled: always

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
#      use-new-id-generator-mappings: false
    generate-ddl: false
    properties:
      hibernate.format_sql: true
#      hibernate.jdbc.batch_size: 10
#      hibernate.jdbc.batch_versioned_data: true
#      hibernate.order_insert: true
#      hibernate.order_update: true
#      hibernate.enable_lazy_load_no_trans: true

      # 설정 정보는 여기 링크 (https://docs.jboss.org/envers/docs/)
      org:
        hibernate:
          envers:
            audit_table_suffix: "_HISTORY"
            revision_field_name: "REVISION_ID"
            revision_type_field_name: "REVISION_TYPE"
  security:
    user:
      name: kimbs
      password: kimbs

  devtools:
    livereload:
      enabled: true


logging:
  level:
    com.querydsl.sql: trace
    org.hibernate.type: trace
#  config: file:${user.dir}/logback-spring.xml
  config: classpath:logback-spring.xml


imc:
  admin:
    # super admin ip list
    super-admin-ip-list:
      - "0:0:0:0:0:0:0:1"
      -
    security:
      default-view-url: "/index.html"
      permit-all-url:
        - "/login/**"
        - "/logout/**"
      login-url: "/login"
      logout-url: "/logout"
      static-resources:
        - "/static/css/**"
        - "/static/fonts/**"
        - "/static/img/**"
        - "/static/js/**"
        - "./favicon.ico"
      role-manage-url:
        - "/admin/**"
