server:
  port: 9999
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    #    hikari:
    url: jdbc:mariadb://localhost:3306/imc_admin?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate.format_sql: true

  security:
    user:
      name: kimbs
      password: kimbs

  devtools:
    livereload:
      enabled: true


logging:
  level:
    com.querydsl.sql: trace
    org.hibernate.type: trace

