################################################################################
# IMC NETTY CLIENT DEMO APPLICATION ver.0.9.0
################################################################################

spring:
  # 아래 경로에 pid 기록
  pid:
    file: ./IMC-NETTY-CLIENT-DEMO.pid

  application:
    name: "IMC-NETTY-CLIENT-DEMO"

  output:
    ansi:
      enabled: ALWAYS

  main:
    web-application-type: SERVLET

server:
  port: 50000

# Client Option
channel:
  client:
    auth-server:
      host: 127.0.0.1
      port: 54321
      id: kimbs
      password: pwkimbs
    timeout-ms: 3000
    # SECONDS
    heartbeat-interval-ms: 3000

