################################################################################
# IMC NETTY CLIENT DEMO APPLICATION ver.0.9.0
################################################################################

spring:
  # 아래 경로에 pid 기록
  pid:
    file: ./application.pid

  application:
    name: "IMC-NETTY-CLIENT-DEMO"

  output:
    ansi:
      enabled: ALWAYS

  main:
    web-application-type: SERVLET

server:
  port: 8080

# Client Option
channel:
  client:
    auth-server:
      host: 119.207.76.90
      port: 32000
      id: devimc
      password: pwdevimc
    timeout-ms: 3000
