################################################################################
# IMC NETTY CLIENT DEMO APPLICATION ver.0.9.0
################################################################################

spring:
  application:
    name: "IMC-NETTY-CLIENT-DEMO"

server:
  port: 8080

# Client Option
channel:
  client:
    auth-server:
      host: 119.207.76.90
      port: 32000
      id: devimc
      password: pwdevimc
    timeout-ms: 3000
