
spring:
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    consumer:
      group-id: kimbs
      enable-auto-commit: false
      max-poll-records: 500
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      concurrency: 5
      ack-mode: manual-immediate
      poll-timeout: 3000
      batch: true

server:
  port: 8081
