
spring:
  output:
    ansi:
      enabled: ALWAYS

  kafka:
    # 카프카 설치 서버
    bootstrap-servers:
      - 127.0.0.1:9092
    consumer:
      # 컨슈머 그룹 아이디
      group-id: kimbs
      # 자동 커밋 설정
      enable-auto-commit: false
      # enable-auto-commit이 true 일 경우 설정 가능
#      auto-commit-interval:
      # 한번에 최대로 읽을 수 있는 양
      max-poll-records: 500
      # Key, Value Serializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Consumer가 값을 읽어올 Partition에 대한 유요한 offset이 없을 때 사용된다.
      # lastest, earliest, none
#      auto-offset-reset:
#      client-id:
#      fetch-max-wait:
#      heartbeat-interval:
      # Kafka Transaction 격리 수준
      isolation-level: READ_COMMITTED

      # 여긴 좀 공부하고 추가
#      ssl:
#        key-password:
#        key-store-location:
#        key-store-password:
#        key-store-type:
#        protocol:
#        trust-store-location:
#        trust-store-password:
#        trust-store-type:

    listener:
      # @KafkaListener 를 실행시키는 쓰레드의 갯수(?)
      concurrency: 1
      # ack mode (manual-immediate, manual, batch, count, count_time, record, time)
      ack-mode: manual-immediate
      poll-timeout: 3000
      # KafkaProperties 에는 없음 - Kafka config 에서 사용 중
      batch: true

      # ListenerFactory 에서 .setBatchListener(true); 한거랑 차이점이 있을까?
      type: BATCH


server:
  port: 8082