
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/querydsl?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: 'create-drop'
    generate-ddl: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
