
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/acquire;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    ddl-auto: 'create-drop'

logging:
  level:
    org:
      hibernate:
        type: trace